CREATE TABLE USERS (
    -- USER_ID será la clave primaria y se autoincrementará
    USER_ID NUMBER GENERATED BY DEFAULT AS IDENTITY,
    -- NOMBRE y APELLIDOS, con un máximo de 40 caracteres
    FIRST_NAME VARCHAR2(40) NOT NULL,
    LAST_NAME VARCHAR2(40) NOT NULL,
    -- EMAIL 
    EMAIL VARCHAR2(40) UNIQUE NOT NULL,
    -- PASSWORD 
    PASSWORD VARCHAR2(255) NOT NULL,
    -- MATRICULA 
    MATRICULA VARCHAR2(20) UNIQUE NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_USERS PRIMARY KEY (USER_ID)
);

COMMENT ON TABLE USERS IS 'Tabla para almacenar la información de los usuarios de Stock Manager.';

COMMENT ON COLUMN USERS.USER_ID IS 'Identificador único y clave primaria del usuario.';
COMMENT ON COLUMN USERS.FIRST_NAME IS 'Nombre(s) del usuario.';
COMMENT ON COLUMN USERS.LAST_NAME IS 'Apellidos del usuario.';
COMMENT ON COLUMN USERS.EMAIL IS 'Dirección de correo electrónico, debe ser única.';
COMMENT ON COLUMN USERS.PASSWORD IS 'Contraseña del usuario (debe ser hasheada para seguridad).';
COMMENT ON COLUMN USERS.MATRICULA IS 'Número de matrícula o identificador único del usuario.';
COMMENT ON COLUMN USERS.CREATED_AT IS 'Fecha y hora de creación del registro de usuario.';